//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_list
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_list()
        {
            this.products_in_order = new HashSet<products_in_order>();
        }
    
        public int o_id { get; set; }
        public System.DateTime o_date { get; set; }
        public short o_status { get; set; }
        public string o_address { get; set; }
        public short payment { get; set; }
        public string image_slip { get; set; }
        public short total_price { get; set; }
        public string line_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products_in_order> products_in_order { get; set; }
    }
}
