//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_in_order
    {
        public int o_id { get; set; }
        public int p_id { get; set; }
        public short quantity { get; set; }
    
        public virtual order_list order_list { get; set; }
        public virtual product product { get; set; }
    }
}
